//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_WASD___Game_Store_Stock_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string GameTitle { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> InStockAmount { get; set; }
        public string Genre { get; set; }
        public string Platform { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
